---
title: "Peripheral neuropathy gene set analysis"
author: "Clemens Hug"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(data.table)
library(synExtra)
library(qs)
library(powerjoin)

synapser::synLogin()
syn <- synDownloader(normalizePath("~/data"), .cache = TRUE)
```

## Reading DEA results

DEA performed by Riki Kawaguchi from UCLA

```{r}
de_raw <- syn("syn63837982") %>%
  readxl::read_excel()


de_long <- de_raw %>%
  select(
    -c(F, F.pValue, AvgExpr, matches("S[0-9]+_.+"))
  ) %>%
  pivot_longer(
    -c(gene_id, gene_name, gene_type, Description, chromosome, strand),
    names_to = c("metric", "contrast"),
    names_pattern = "(.*?)_(.*)",
    values_to = "value"
  ) %>%
  pivot_wider(
    names_from = metric,
    values_from = value
  ) %>%
  mutate(
    FDR_min_zero = if_else(FDR == 0, min(FDR[FDR > 0]) * .5, FDR),
    signed_padj = -sign(logFC) * log10(FDR_min_zero)
  )
  # separate_longer_delim(
  #   -c(gene_id, gene_name, gene_type, Description, chromosome, strand),
  #   delim = regex("(?<=^[^_]*)_")
  # )
```


```{r}
dplyr::distinct(de_long, contrast)

contrast_map <- c(
  "GNE.495.DMSO_vs_DMSO" = "GNE-495",
  "JNK.inh.DMSO_vs_DMSO" = "JNK-inh",
  "GNE.495.PTX_vs_DMSO" = "GNE-495 + PTX",
  "JNK.inh.PTX_vs_DMSO" = "JNK-inh + PTX",
  "PTX_vs_DMSO" = "PTX",
  "GNE.495.PTX_vs_PTX" = "GNE-495 + PTX vs PTX",
  "JNK.inh.PTX_vs_PTX" = "JNK-inh + PTX vs PTX"
)

de_long_selected <- de_long %>%
  filter(contrast %in% names(contrast_map)) %>%
  mutate(contrast = contrast_map[contrast])
```

PTX rescue

```{r}
clamp_symbols <- \(x, symbols, threshold) {
  case_when(
    abs(x) < threshold ~ "point",
    x > 0 ~ symbols[1],
    x < 0 ~ symbols[2],
    TRUE ~ NA_character_
  )
}

ptx_rescue_plot_data <- tribble(
  ~contrast_1, ~contrast_2,
  "PTX", "GNE-495 + PTX",
  "PTX", "JNK-inh + PTX"
) %>%
  power_inner_join(
    de_long_selected %>%
      select(gene_id, logFC, PValue, FDR, FDR_min_zero, signed_padj, contrast),
    by = c("contrast_1" = "contrast"),
    check = check_specs(
      unmatched_keys_left = "warn"
    )
  ) %>%
  power_inner_join(
    de_long_selected %>%
      select(gene_id, logFC, PValue, FDR, FDR_min_zero, signed_padj, contrast),
    by = c("contrast_2" = "contrast", "gene_id"),
    suffix = c("_1", "_2"),
    check = check_specs(
      unmatched_keys_left = "warn",
      duplicate_keys_left = "warn",
      duplicate_keys_right = "warn"
    )
  ) %>%
  mutate(
    across(
      starts_with("signed_padj"),
      list(
        clamped = \(x) if_else(abs(x) > 100, sign(x) * 100, x),
        symbol = \(x) clamp_symbols(x, if (cur_column() == "signed_padj_1") c("left", "right") else c("up", "down"), 100)
      )
    ),
    signed_padj_symbol = case_when(
      !xor(signed_padj_1_symbol == "point", signed_padj_2_symbol == "point") ~ "point",
      signed_padj_1_symbol != "point" ~ signed_padj_1_symbol,
      signed_padj_2_symbol != "point" ~ signed_padj_2_symbol,
      TRUE ~ NA_character_
    )
  )
```


```{r}
p <- ggplot(
  ptx_rescue_plot_data,
  aes(
    x = signed_padj_1_clamped,
    y = signed_padj_2_clamped,
    shape = signed_padj_symbol
  )
) +
  geom_abline() +
  geom_point(
    alpha = 0.5
  ) +
  scale_shape_manual(
    values = c(point = "\u25CF", right = "\u25BA", left = "\u25C4", down = "\u25BC", up = "\u25B2"),
    guide = "none"
  ) +
  ggh4x::facet_wrap2(
    ~contrast_2,
    scales = "free", axes = "all"
  ) +
  labs(
    x = "Signed log10(padj) Paclitaxel",
    y = "Signed log10(padj) Rescue"
  )

dir.create("plots", showWarnings = FALSE)
ggsave(
  file.path("plots", "ptx_rescue_scatter.pdf"),
  p, width = 7, height = 4, device = cairo_pdf
)


p <- ggplot(
  ptx_rescue_plot_data,
  aes(
    x = logFC_1,
    y = logFC_2
  )
) +
  geom_abline() +
  geom_point(
    alpha = 0.5,
    shape = "circle small"
  ) +
  ggh4x::facet_wrap2(
    ~contrast_2,
    scales = "free", axes = "all"
  ) +
  labs(
    x = "log2(FC) Paclitaxel",
    y = "log2(FC) Rescue"
  )

dir.create("plots", showWarnings = FALSE)
ggsave(
  file.path("plots", "ptx_rescue_logFC_scatter.pdf"),
  p, width = 7, height = 4, device = cairo_pdf
)
```


```{r}
de_long_selected_wide <- de_long_selected %>%
  pivot_wider(
    names_from = contrast,
    values_from = c(logFC, PValue, FDR, LR, logCPM, FDR_min_zero, signed_padj)
  )


```


Make alluvial diagram of PTX rescue

First approach:

- Find genes up or down in PTX treatment, identify those that are rescued by at
lest 1 logs in GNE-495 + PTX or JNK-inh + PTX

```{r}
RECOVERY_THRESHOLD <- 1

pax_rescue_list <- de_long_selected_wide %>%
  mutate(
    across(
      matches("logFC_.*vs PTX"),
      list(
        logFC_recovery = \(x) x - logFC_PTX
      )
    )
  ) %>%
  mutate(
    `GNE-495 + PTX perturbed` = case_when(
      `FDR_GNE-495 + PTX` > .05 ~ "not perturbed",
      `logFC_GNE-495 + PTX` > 0 ~ "up",
      `logFC_GNE-495 + PTX` < 0 ~ "down",
      TRUE ~ NA_character_
    ),
    `JNK-inh + PTX perturbed` = case_when(
      `FDR_JNK-inh + PTX` > .05 ~ "not perturbed",
      `logFC_JNK-inh + PTX` > 0 ~ "up",
      `logFC_JNK-inh + PTX` < 0 ~ "down",
      TRUE ~ NA_character_
    ),
    `PTX perturbed` = case_when(
      FDR_PTX > .05 ~ "not perturbed",
      logFC_PTX > 0 ~ "up",
      logFC_PTX < 0 ~ "down",
      TRUE ~ NA_character_
    ),
    `GNE-495 + PTX rescue` = case_when(
      is.na(`PTX perturbed`) | `PTX perturbed` == "not perturbed" ~ "not perturbed",
      `PTX perturbed` == "up" & `FDR_GNE-495 + PTX vs PTX` < .05 & `logFC_GNE-495 + PTX vs PTX` < 0 ~ "up rescued",
      `PTX perturbed` == "down" & `FDR_GNE-495 + PTX vs PTX` < .05 & `logFC_GNE-495 + PTX vs PTX` > 0 ~ "down rescued",
      TRUE ~ paste(`PTX perturbed`, "unrescued", sep = " ")
    ),
    `JNK-inh + PTX rescue` = case_when(
      is.na(`PTX perturbed`) | `PTX perturbed` == "not perturbed" ~ "not perturbed",
      `PTX perturbed` == "up" & `FDR_JNK-inh + PTX vs PTX` < .05 & `logFC_JNK-inh + PTX vs PTX` < 0 ~ "up rescued",
      `PTX perturbed` == "down" & `FDR_JNK-inh + PTX vs PTX` < .05 & `logFC_JNK-inh + PTX vs PTX` > 0 ~ "down rescued",
      TRUE ~ paste(`PTX perturbed`, "unrescued", sep = " ")
    ),
    `GNE-495 + PTX rescue DMSO` = case_when(
      is.na(`PTX perturbed`) | `PTX perturbed` == "not perturbed" ~ "not perturbed",
      `PTX perturbed` == "up" & `FDR_GNE-495 + PTX` > .05 ~ "up rescued",
      `PTX perturbed` == "down" & `FDR_GNE-495 + PTX` > .05 ~ "down rescued",
      TRUE ~ paste(`PTX perturbed`, "unrescued", sep = " ")
    ),
    `JNK-inh + PTX rescue DMSO` = case_when(
      is.na(`PTX perturbed`) | `PTX perturbed` == "not perturbed" ~ "not perturbed",
      `PTX perturbed` == "up" & `FDR_JNK-inh + PTX` > .05 ~ "up rescued",
      `PTX perturbed` == "down" & `FDR_JNK-inh + PTX` > .05 ~ "down rescued",
      TRUE ~ paste(`PTX perturbed`, "unrescued", sep = " ")
    ),
    `GNE-495 + PTX rescue DMSO plus` = case_when(
      is.na(`PTX perturbed`) | `PTX perturbed` == "not perturbed" ~ "not perturbed",
      `PTX perturbed` == "up" & (`FDR_GNE-495 + PTX` > .05 | `logFC_GNE-495 + PTX` < 0) ~ "up rescued",
      `PTX perturbed` == "down" & (`FDR_GNE-495 + PTX` > .05 | `logFC_GNE-495 + PTX` > 0) ~ "down rescued",
      TRUE ~ paste(`PTX perturbed`, "unrescued", sep = " ")
    ),
    `JNK-inh + PTX rescue DMSO plus` = case_when(
      is.na(`PTX perturbed`) | `PTX perturbed` == "not perturbed" ~ "not perturbed",
      `PTX perturbed` == "up" & (`FDR_JNK-inh + PTX` > .05 | `logFC_JNK-inh + PTX` < 0) ~ "up rescued",
      `PTX perturbed` == "down" & (`FDR_JNK-inh + PTX` > .05 | `logFC_JNK-inh + PTX` > 0) ~ "down rescued",
      TRUE ~ paste(`PTX perturbed`, "unrescued", sep = " ")
    ),
    # `GNE-495 + PTX_rescue` = case_when(
    #   is.na(PTX_perturbed) | PTX_perturbed == "not perturbed" ~ "not perturbed",
    #   PTX_perturbed == "up" & `logFC_GNE-495 + PTX vs PTX_logFC_recovery` < -RECOVERY_THRESHOLD ~ "up_recovered",
    #   PTX_perturbed == "down" & `logFC_GNE-495 + PTX vs PTX_logFC_recovery` > RECOVERY_THRESHOLD ~ "down_recovered",
    #   TRUE ~ paste(PTX_perturbed, "unrecovered", sep = "_")
    # ),
    # `JNK-inh + PTX_rescue` = case_when(
    #   is.na(PTX_perturbed) | PTX_perturbed == "not perturbed" ~ "not perturbed",
    #   PTX_perturbed == "up" & `logFC_JNK-inh + PTX vs PTX_logFC_recovery` < -RECOVERY_THRESHOLD ~ "up_recovered",
    #   PTX_perturbed == "down" & `logFC_JNK-inh + PTX vs PTX_logFC_recovery` > RECOVERY_THRESHOLD ~ "down_recovered",
    #   TRUE ~ paste(PTX_perturbed, "unrecovered", sep = "_")
    # )
  )

pax_rescue_list_simple <- pax_rescue_list %>%
  filter(`PTX perturbed` != "not perturbed") %>%
  transmute(
    gene_id, gene_name, gene_type,
    across(ends_with(" perturbed")),
    across(
      ends_with(" rescue"),
      # \(x) str_replace(x, " unrescued", "") %>%
      \(x) str_replace(x, "up unrescued", "no rescue") %>%
        str_replace("down unrescued", "no rescue") %>%
        str_replace("up rescued", "rescued") %>%
        str_replace("down rescued", "rescued")
    ),
    `Rescue type` = case_when(
      `GNE-495 + PTX rescue` == "rescued" & `JNK-inh + PTX rescue` == "rescued" ~ "both",
      `GNE-495 + PTX rescue` == "rescued" ~ "GNE-495 only rescue",
      `JNK-inh + PTX rescue` == "rescued" ~ "JNK-inh only rescue",
      TRUE ~ "no rescue"
    )
  )
```


```{r}
ptx_rescue_plot_data_w_type <- ptx_rescue_plot_data %>%
  left_join(
    pax_rescue_list_simple %>%
      select(-gene_name, -gene_type),
    by = "gene_id"
  ) %>%
  mutate(
    `Rescue type` = replace_na(`Rescue type`, "not perturbed") %>%
      factor(
        levels = c(
          "both",
          "JNK-inh only rescue",
          "GNE-495 only rescue",
          "no rescue",
          "not perturbed"
        )
      )
  )

p <- ggplot(
  ptx_rescue_plot_data %>%
    left_join(
      pax_rescue_list_simple %>%
        select(-gene_name, -gene_type),
      by = "gene_id"
    ) %>%
    mutate(
      `Rescue type` = replace_na(`Rescue type`, "not perturbed")
    ) %>%
    filter(`Rescue type` != "not perturbed") %>%
    arrange(desc(`Rescue type`)),
  aes(
    x = signed_padj_1_clamped,
    y = signed_padj_2_clamped,
    shape = signed_padj_symbol,
    color = `Rescue type`
  )
) +
  geom_abline() +
  geom_point(
    alpha = 0.5
  ) +
  scale_shape_manual(
    values = c(point = "\u25CF", right = "\u25BA", left = "\u25C4", down = "\u25BC", up = "\u25B2"),
    guide = "none"
  ) +
  scale_color_manual(
    values = c(
      both = "black",
      `JNK-inh only rescue` = "purple",
      `GNE-495 only rescue` = "green",
      `no rescue` = "gray85"
    )
  ) +
  ggh4x::facet_wrap2(
    ~contrast_2,
    scales = "free", axes = "all"
  ) +
  labs(
    x = "Signed log10(padj) Paclitaxel",
    y = "Signed log10(padj) Rescue"
  )

dir.create("plots", showWarnings = FALSE)
ggsave(
  file.path("plots", "ptx_rescue_scatter_w_rescue_type.pdf"),
  p, width = 8, height = 4, device = cairo_pdf
)


p <- ggplot(
  ptx_rescue_plot_data %>%
    left_join(
      pax_rescue_list_simple %>%
        select(-gene_name, -gene_type),
      by = "gene_id"
    ) %>%
    mutate(
      `Rescue type` = replace_na(`Rescue type`, "not perturbed")
    ) %>%
    filter(`Rescue type` != "not perturbed") %>%
    arrange(desc(`Rescue type`)),
  aes(
    x = logFC_1,
    y = logFC_2,
    # shape = signed_padj_symbol,
    color = `Rescue type`
  )
) +
  geom_abline() +
  geom_point(
    alpha = 0.5,
    shape = "circle small"
  ) +
  scale_color_manual(
    values = c(
      both = "black",
      `JNK-inh only rescue` = "purple",
      `GNE-495 only rescue` = "green",
      `no rescue` = "gray85"
    )
  ) +
  ggh4x::facet_wrap2(
    ~contrast_2,
    scales = "free", axes = "all"
  ) +
  labs(
    x = "log2(fold-change) Paclitaxel",
    y = "log2(fold-change) Rescue"
  )

dir.create("plots", showWarnings = FALSE)
ggsave(
  file.path("plots", "ptx_rescue_scatter_logFC_w_rescue_type.pdf"),
  p, width = 8, height = 4, device = cairo_pdf
)
```

```{r}
fpkm_raw <- syn("syn63854603") %>%
  read_csv()

fpkm_long <- fpkm_raw %>%
  pivot_longer(
    -c(gene_id, gene_name, gene_type, Description, chromosome, strand),
    names_to = c("sample_id", "condition", "metric"),
    names_pattern = "(S[0-9]+?)_(.*?) ?\\.(.*)",
    values_to = "value"
  )

fpkm_long$condition %>%
  unique()
```

```{r}
selected_genes <- withr::with_seed(
  42,
  pax_rescue_list_simple %>%
    group_by(
      `Rescue type`,
      `PTX perturbed`
    ) %>%
    slice_sample(n = 3) %>%
    ungroup()
)


conditions_of_interest <- c(
  "DMSO",
  "PTX",
  "JNKinhPTX",
  "GNE495PTX"
)

library(ggbeeswarm)

selected_genes_fpkm <- selected_genes %>%
  inner_join(
    fpkm_long %>%
      filter(
        condition %in% conditions_of_interest
      ) %>%
      mutate(across(condition, \(x) factor(x, levels = conditions_of_interest))),
    by = "gene_id"
  )

p <- ggplot(
  selected_genes_fpkm %>%
    arrange(`Rescue type`) %>%
    mutate(
      gene_name.x = fct_inorder(gene_name.x)
    ),
  aes(
    x = condition,
    y = value,
  )
) +
  geom_rect(
    aes(fill = `Rescue type`),
    xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf, alpha = 0.3,
    inherit.aes = FALSE,
    data = \(x) x %>%
      distinct(gene_name.x, `Rescue type`)
  ) +
  geom_beeswarm() +
  geom_boxplot(
    outlier.shape = NA,
    fill = NA
  ) +
  scale_fill_manual(
    values = c(
      both = "black",
      `JNK-inh only rescue` = "purple",
      `GNE-495 only rescue` = "green",
      `no rescue` = "gray85"
    )
  ) +
  ggh4x::facet_wrap2(~gene_name.x, scales = "free_y", axes = "y") +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +
  labs(y = "FPKM")

ggsave(
  file.path("plots", "selected_genes_fpkm.pdf"),
  p, width = 8, height = 6, device = cairo_pdf
)
```


```{r}
pax_rescue_list %>%
  count(`PTX perturbed`)

pax_rescue_alluvials_simple <- pax_rescue_list %>%
  count(
    `PTX perturbed`,
    `GNE-495 + PTX rescue`,
    `JNK-inh + PTX rescue`
  )

pax_rescue_alluvials <- pax_rescue_list %>%
  count(
    `PTX perturbed`,
    `GNE-495 + PTX perturbed`,
    `JNK-inh + PTX perturbed`,
    `GNE-495 + PTX rescue`,
    `JNK-inh + PTX rescue`
  )

pax_rescue_lodes <- pax_rescue_list_simple %>%
  count(
    `PTX perturbed`,
    `GNE-495 + PTX rescue`,
    `JNK-inh + PTX rescue`
  )
  to_lodes_form(
    c(`PTX perturbed`, `GNE-495 + PTX rescue`, `JNK-inh + PTX rescue`),
    key = "Contrast", value = "Gene set"
  )

p <- ggplot(
  ,
  aes(
    x = Contrast, y = n, stratum = `Gene set`, alluvium = alluvium
  )
) +
  scale_x_discrete(expand = c(0.05, 0.05)) +
  geom_alluvium(
    aes(
      # color = `PTX perturbed 2`,
      fill = `Rescue type`
    ),
    width = 1/10
  ) +
  # ggokabeito::scale_color_okabe_ito(order = c(2, 1), guide = "none") +
  scale_fill_manual(
    values = c(
      both = "black",
      `JNK-inh only rescue` = "purple",
      `GNE-495 only rescue` = "green",
      `no rescue` = "gray85"
    )
  ) +
  labs(x = NULL) +
  # scale_fill_manual(
  #     values = c(existing = "#a2a2a2", added = "#c81919"),
  #     guide = "none"
  # ) +
  geom_stratum(width = 1/6) +
  # geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
  geom_label(stat = "stratum", aes(label = after_stat(stratum))) +
  theme_minimal() +
  # labs(y = "Data points", fill = NA) +
  theme(
      panel.grid.major.x = element_blank()
  ) +
  coord_cartesian(clip = "off")

ggsave(
  file.path("plots", "ptx_rescue_no_threshold_alluvium.pdf"),
  p, width = 6, height = 4
)
```


```{r}
library(ggalluvial)

p <- ggplot(
    pax_rescue_alluvials %>%
      filter(PTX_perturbed != "not perturbed"),
    aes(
      axis1 = `GNE-495 + PTX_perturbed`,
      axis2 = `JNK-inh + PTX_perturbed`,
      axis3 = `GNE-495 + PTX_rescue`,
      axis4 = `JNK-inh + PTX_rescue`,
      y = n
    )
  ) +
  # scale_x_discrete(limits = c("Class", "Sex", "Age"), expand = c(.2, .05)) +
  # xlab("Demographic") +
  # geom_alluvium(aes(fill = Survived)) +
  geom_alluvium() +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
  theme_minimal()


p <- ggplot(
    pax_rescue_alluvials %>%
      filter(PTX_perturbed != "not perturbed") %>%
      mutate(
        across(
          ends_with("_rescue"),
          \(x) str_replace(x, "_unrecovered", "") %>%
            str_replace("up_recovered", "recovered") %>%
            str_replace("down_recovered", "recovered")
        ),
      ),
    aes(
      axis1 = `PTX_perturbed`,
      axis2 = `GNE-495 + PTX_rescue`,
      axis3 = `JNK-inh + PTX_rescue`,
      y = n
    )
  ) +
  # scale_x_discrete(limits = c("Class", "Sex", "Age"), expand = c(.2, .05)) +
  # xlab("Demographic") +
  # geom_alluvium(aes(fill = Survived)) +
  geom_alluvium(
    aes(fill = PTX_perturbed)
  ) +
  ggokabeito::scale_fill_okabe_ito(order = c(2, 1)) +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
  theme_minimal()


p <- ggplot(
    pax_rescue_alluvials %>%
      filter(PTX_perturbed != "not perturbed"),
    aes(
      axis1 = `GNE-495 + PTX_perturbed`,
      axis2 = `JNK-inh + PTX_perturbed`,
      axis3 = `PTX_perturbed`,
      y = n
    )
  ) +
  # scale_x_discrete(limits = c("Class", "Sex", "Age"), expand = c(.2, .05)) +
  # xlab("Demographic") +
  # geom_alluvium(aes(fill = Survived)) +
  geom_alluvium() +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
  theme_minimal()

ggsave(

)
```


```{r}
pax_rescue_list_simple_dmso <- pax_rescue_list %>%
  filter(`PTX perturbed` != "not perturbed") %>%
  transmute(
    gene_id, gene_name, gene_type,
    across(ends_with(" perturbed")),
    across(
      ends_with(" rescue DMSO"),
      # \(x) str_replace(x, " unrescued", "") %>%
      \(x) str_replace(x, "up unrescued", "no rescue") %>%
        str_replace("down unrescued", "no rescue") %>%
        str_replace("up rescued", "rescued") %>%
        str_replace("down rescued", "rescued")
    ),
    `Rescue type` = case_when(
      `GNE-495 + PTX rescue DMSO` == "rescued" & `JNK-inh + PTX rescue DMSO` == "rescued" ~ "both",
      `GNE-495 + PTX rescue DMSO` == "rescued" ~ "GNE-495 only rescue",
      `JNK-inh + PTX rescue DMSO` == "rescued" ~ "JNK-inh only rescue",
      TRUE ~ "no rescue"
    )
  )

```


```{r}
ptx_rescue_plot_data_w_type <- ptx_rescue_plot_data %>%
  left_join(
    pax_rescue_list_simple_dmso %>%
      select(-gene_name, -gene_type),
    by = "gene_id"
  ) %>%
  mutate(
    `Rescue type` = replace_na(`Rescue type`, "not perturbed") %>%
      factor(
        levels = c(
          "both",
          "JNK-inh only rescue",
          "GNE-495 only rescue",
          "no rescue",
          "not perturbed"
        )
      )
  )

p <- ggplot(
  ptx_rescue_plot_data_w_type %>%
    filter(`Rescue type` != "not perturbed") %>%
    arrange(desc(`Rescue type`)),
  aes(
    x = signed_padj_1_clamped,
    y = signed_padj_2_clamped,
    shape = signed_padj_symbol,
    color = `Rescue type`
  )
) +
  geom_abline() +
  geom_point(
    alpha = 0.5
  ) +
  scale_shape_manual(
    values = c(point = "\u25CF", right = "\u25BA", left = "\u25C4", down = "\u25BC", up = "\u25B2"),
    guide = "none"
  ) +
  scale_color_manual(
    values = c(
      both = "black",
      `JNK-inh only rescue` = "purple",
      `GNE-495 only rescue` = "green",
      `no rescue` = "gray85"
    )
  ) +
  ggh4x::facet_wrap2(
    ~contrast_2,
    scales = "free", axes = "all"
  ) +
  labs(
    x = "Signed log10(padj) Paclitaxel",
    y = "Signed log10(padj) Rescue"
  )

dir.create("plots", showWarnings = FALSE)
ggsave(
  file.path("plots", "ptx_rescue_scatter_w_rescue_type_dmso.pdf"),
  p, width = 8, height = 4, device = cairo_pdf
)


p <- ggplot(
  ptx_rescue_plot_data_w_type %>%
    filter(`Rescue type` != "not perturbed") %>%
    arrange(desc(`Rescue type`)),
  aes(
    x = logFC_1,
    y = logFC_2,
    # shape = signed_padj_symbol,
    color = `Rescue type`
  )
) +
  geom_abline() +
  geom_point(
    alpha = 0.5,
    shape = "circle small"
  ) +
  scale_color_manual(
    values = c(
      both = "black",
      `JNK-inh only rescue` = "purple",
      `GNE-495 only rescue` = "green",
      `no rescue` = "gray85"
    )
  ) +
  ggh4x::facet_wrap2(
    ~contrast_2,
    scales = "free", axes = "all"
  ) +
  labs(
    x = "log2(fold-change) Paclitaxel",
    y = "log2(fold-change) Rescue"
  )

dir.create("plots", showWarnings = FALSE)
ggsave(
  file.path("plots", "ptx_rescue_scatter_logFC_w_rescue_type_dmso.pdf"),
  p, width = 8, height = 4, device = cairo_pdf
)
```



```{r}
pax_rescue_list_simple_dmso_plus <- pax_rescue_list %>%
  filter(`PTX perturbed` != "not perturbed") %>%
  transmute(
    gene_id, gene_name, gene_type,
    across(ends_with(" perturbed")),
    across(
      ends_with(" rescue DMSO plus"),
      # \(x) str_replace(x, " unrescued", "") %>%
      \(x) str_replace(x, "up unrescued", "no rescue") %>%
        str_replace("down unrescued", "no rescue") %>%
        str_replace("up rescued", "rescued") %>%
        str_replace("down rescued", "rescued")
    ),
    `Rescue type` = case_when(
      `GNE-495 + PTX rescue DMSO plus` == "rescued" & `JNK-inh + PTX rescue DMSO plus` == "rescued" ~ "both",
      `GNE-495 + PTX rescue DMSO plus` == "rescued" ~ "GNE-495 only rescue",
      `JNK-inh + PTX rescue DMSO plus` == "rescued" ~ "JNK-inh only rescue",
      TRUE ~ "no rescue"
    )
  )

```


```{r}
ptx_rescue_plot_data_w_type <- ptx_rescue_plot_data %>%
  left_join(
    pax_rescue_list_simple_dmso_plus %>%
      select(-gene_name, -gene_type),
    by = "gene_id"
  ) %>%
  mutate(
    `Rescue type` = replace_na(`Rescue type`, "not perturbed") %>%
      factor(
        levels = c(
          "both",
          "JNK-inh only rescue",
          "GNE-495 only rescue",
          "no rescue",
          "not perturbed"
        )
      )
  )

p <- ggplot(
  ptx_rescue_plot_data_w_type %>%
    filter(`Rescue type` != "not perturbed") %>%
    arrange(desc(`Rescue type`)),
  aes(
    x = signed_padj_1_clamped,
    y = signed_padj_2_clamped,
    shape = signed_padj_symbol,
    color = `Rescue type`
  )
) +
  geom_abline() +
  geom_point(
    alpha = 0.5
  ) +
  scale_shape_manual(
    values = c(point = "\u25CF", right = "\u25BA", left = "\u25C4", down = "\u25BC", up = "\u25B2"),
    guide = "none"
  ) +
  scale_color_manual(
    values = c(
      both = "black",
      `JNK-inh only rescue` = "purple",
      `GNE-495 only rescue` = "green",
      `no rescue` = "gray85"
    )
  ) +
  ggh4x::facet_wrap2(
    ~contrast_2,
    scales = "free", axes = "all"
  ) +
  labs(
    x = "Signed log10(padj) Paclitaxel",
    y = "Signed log10(padj) Rescue"
  )

dir.create("plots", showWarnings = FALSE)
ggsave(
  file.path("plots", "ptx_rescue_scatter_w_rescue_type_dmso_plus.pdf"),
  p, width = 8, height = 4, device = cairo_pdf
)


p <- ggplot(
  ptx_rescue_plot_data_w_type %>%
    filter(`Rescue type` != "not perturbed") %>%
    arrange(desc(`Rescue type`)),
  aes(
    x = logFC_1,
    y = logFC_2,
    # shape = signed_padj_symbol,
    color = `Rescue type`
  )
) +
  geom_abline() +
  geom_point(
    alpha = 0.5,
    shape = "circle small"
  ) +
  scale_color_manual(
    values = c(
      both = "black",
      `JNK-inh only rescue` = "purple",
      `GNE-495 only rescue` = "green",
      `no rescue` = "gray85"
    )
  ) +
  ggh4x::facet_wrap2(
    ~contrast_2,
    scales = "free", axes = "all"
  ) +
  labs(
    x = "log2(fold-change) Paclitaxel",
    y = "log2(fold-change) Rescue"
  )

dir.create("plots", showWarnings = FALSE)
ggsave(
  file.path("plots", "ptx_rescue_scatter_logFC_w_rescue_type_dmso_plus.pdf"),
  p, width = 8, height = 4, device = cairo_pdf
)
```
